name: Node.js App
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        run: npm install
      - name: Run Node.js
        run: npm start
